version: "3"

services:
#  backend:
#    image: backend:latest
#    build:
#      context: ./backend
#      dockerfile: Dockerfile
#    ports:
#      - "8080:8080"
#    volumes:
#      - ./data/files:/app/data/files
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/homework_manager
#      SPRING_DATASOURCE_USERNAME: user
#      SPRING_DATASOURCE_PASSWORD: password
#      SPRING_JPA_HIBERNATE_DDL_AUTO: update
#      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
#    depends_on:
#      - db
  db:
    image: mysql:8.4
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homework_manager
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "13306:3306"
    volumes:
      - ./data/db:/var/lib/mysql