spring:
    application:
        name: backend
    mvc:
        converters:
            preferred-json-mapper: gson
        static-path-pattern: /**

    web:
        locale: en
        resources:
            static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/,classpath:/resources/static/,classpath:/resources/public/,classpath:/resources/resources/,classpath:/resources/META-INF/resources/
    jpa:
        database: mysql
        hibernate:
            ddl-auto: update
        properties:
            hibernate.hibernate.dialect: org.hibernate.dialect.MySQL8Dialect
    datasource:
        url: jdbc:mysql://localhost:13306/homework_manager
        username: user
        password: password
server:
    port: 8080
    cors:
        allowed-origins: []

security:
    salt: homework-salt